In [2]:
#Importing Weather Dataset
import pandas as pd
data = pd.read_csv(r"C:\Users\jassv\Desktop\Python_folder\resource\Project+1+-+Weather+Dataset.csv")
data

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather
0,1/1/2012 0:00,-1.8,-3.9,86,4,8.0,101.24,Fog
1,1/1/2012 1:00,-1.8,-3.7,87,4,8.0,101.24,Fog
2,1/1/2012 2:00,-1.8,-3.4,89,7,4.0,101.26,"Freezing Drizzle,Fog"
3,1/1/2012 3:00,-1.5,-3.2,88,6,4.0,101.27,"Freezing Drizzle,Fog"
4,1/1/2012 4:00,-1.5,-3.3,88,7,4.8,101.23,Fog
...,...,...,...,...,...,...,...,...
8779,12/31/2012 19:00,0.1,-2.7,81,30,9.7,100.13,Snow
8780,12/31/2012 20:00,0.2,-2.4,83,24,9.7,100.03,Snow
8781,12/31/2012 21:00,-0.5,-1.5,93,28,4.8,99.95,Snow
8782,12/31/2012 22:00,-0.2,-1.8,89,28,9.7,99.91,Snow
8783,12/31/2012 23:00,0.0,-2.1,86,30,11.3,99.89,Snow

In [3]:
#head show case
data.head()

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather
0,1/1/2012 0:00,-1.8,-3.9,86,4,8.0,101.24,Fog
1,1/1/2012 1:00,-1.8,-3.7,87,4,8.0,101.24,Fog
2,1/1/2012 2:00,-1.8,-3.4,89,7,4.0,101.26,"Freezing Drizzle,Fog"
3,1/1/2012 3:00,-1.5,-3.2,88,6,4.0,101.27,"Freezing Drizzle,Fog"
4,1/1/2012 4:00,-1.5,-3.3,88,7,4.8,101.23,Fog

In [5]:
#shape show case
data.shape

(8784, 8)

In [10]:
#index show case
data.index

RangeIndex(start=0, stop=8784, step=1)

In [11]:
#type show case
data.dtypes

Date/Time            object
Temp_C              float64
Dew Point Temp_C    float64
Rel Hum_%             int64
Wind Speed_km/h       int64
Visibility_km       float64
Press_kPa           float64
Weather              object
dtype: object

In [16]:
#Cover which values are unique
data['Temp_C'].unique()

array([ -1.8,  -1.5,  -1.4,  -1.3,  -1. ,  -0.5,  -0.2,   0.2,   0.8,
         1.8,   2.6,   3. ,   3.8,   3.1,   3.2,   4. ,   4.4,   5.3,
         5.2,   4.6,   3.9,   3.7,   2.9,   2.3,   2. ,   1.9,   1.5,
         2.2,   1.7,   1.1,   0. ,  -0.7,  -2.1,  -4.1,  -4.8,  -5.6,
        -5.8,  -7. ,  -7.4,  -9. ,  -9.7, -10.5, -11.3, -12.6, -12.9,
       -13.3, -14. , -14.8, -15. , -15.3, -14.9, -15.1, -15.8, -16.3,
       -16.9, -17.3, -17. , -17.1, -17.5, -17.9, -18.1, -18.5, -18.6,
       -18.2, -17.8, -16.8, -15.2, -14.2, -13.7, -12.4, -10.2,  -9.4,
        -8.9,  -8.4,  -7.8,  -7.6,  -9.5,  -9.6,  -8.8,  -7.5,  -5.4,
        -5. ,  -8.2,  -7.1,  -6.1,  -6.6,  -6. ,  -4.7,  -4.4,  -5.1,
        -4.3,  -6.7,  -9.2,  -9.8,  -9.9, -10. , -10.6, -11.8, -12. ,
       -14.4, -12.3, -12.5, -11.7, -11.9, -11.2, -11.5, -11.6,  -9.3,
        -8.7,  -8.5,  -8.1,  -6.9,  -6.4,  -5.7,  -5.5,  -3.7,  -3.6,
        -3.1,  -3.2,  -3. ,   0.4,   0.6,  -0.6,  -1.7,  -3.5,  -5.9,
        -6.5,  -7.2,  -8. ,  -8.3,  -7.7,  -6.8,  -2.5,  -1.1,  -0.3,
         2.5,   1.4,   1.6,   1.2,   0.7,  -4. ,  -4.9,  -7.3,  -8.6,
       -10.7, -12.7, -13.4, -13.9, -14.7, -14.3, -12.2, -11.4, -10.8,
        -6.2,  -5.2,  -4.6,  -4.5,  -2.9, -18. , -16.7, -17.4, -17.7,
       -18.3, -19.6, -20. , -19.9, -20.3, -21.2, -21.1, -21.4, -20.7,
       -21. , -21.3, -23.2, -22.8, -23.3, -22.2, -20.6, -19.3, -16. ,
       -15.4, -16.2, -19.2, -18.7, -19.1, -13.6, -10.1, -10.4,  -5.3,
        -3.3,  -1.6,   2.1,   0.5, -10.9, -11.1, -11. , -10.3, -16.6,
       -14.6,  -4.2,  -3.9,  -6.3, -15.5, -15.9, -16.4, -16.1, -12.1,
       -13. , -17.6, -18.4, -17.2, -19.5, -19. , -14.5, -13.2,   2.7,
         3.3,   3.6,   3.5,   5. ,   4.2,   3.4,   2.8,   2.4,   1.3,
         1. ,  -0.1,  -0.4,  -2.8,  -7.9,  -3.4,  -3.8,  -0.8,   0.3,
         0.1,  -1.2,   0.9,  -0.9,  -2. ,  -1.9,  -2.2,  -2.3, -15.7,
       -13.5, -13.8,  -2.4, -13.1, -12.8,  -2.7,   5.8,   6.1,   5.4,
         6.5,   4.3,   6.4,   8.9,   9.3,   9.7,  11.4,   9.9,   5.5,
         6. ,   7.6,   6.8,   4.8,   6.2,   7.9,  10.1,  10. ,   5.7,
        10.3,   6.7,  10.2,  12.1,  12.7,  11.7,  11.5,  11.6,  11.3,
        10.5,  -2.6,   5.9,   9. ,   9.5,  10.9,  10.7,   9.1,   7.4,
         8.3,  10.6,  10.8,  12.3,  12.4,  11.8,   8.7,   9.2,   8.4,
         6.6,   7.5,   5.1,   4.9,   4.1,   8.1,   9.8,   8.8,   7.7,
        10.4,  11.9,  14.1,  17.3,  20. ,  21.7,  22.2,  22.7,  21.8,
        18.4,  17.1,  12.8,  13.4,  12.6,  11.2,  13.9,  15.6,  17.8,
        19.8,  18.5,  17. ,  16.3,  16.6,  15.9,  12.5,   7.2,   7.1,
         8. ,  14.9,  16.5,  21.5,  22.5,  23.3,  22. ,  19.7,  17.5,
        18.1,  16. ,  14.2,  14.3,  14. ,  13.8,  18.2,  20.2,  22.3,
        23.8,  24.7,  25.4,  25.5,  25.2,  20.7,  17.2,  16.4,  18. ,
        15.5,  15. ,  11. ,  13.2,  13.7,  15.4,  19.6,  20.4,  23. ,
        22.8,  21.4,  16.7,  15.1,  14.5,  16.2,  16.8,  14.7,   7.3,
         4.7,   6.3,   4.5,   8.2,   7. ,   6.9,   7.8,   5.6,   8.5,
         8.6,   9.4,  12.2,  13.5,  16.1,  13.6,  15.3,  14.8,  12. ,
        12.9,  13.1,  19.4,  14.6,  15.7,  14.4,  15.2,  19.3,  24.9,
        24.1,  24.8,  26.6,  27.4,  27.8,  27.3,  26.7,  26.4,  20.5,
        19.5,  19. ,  18.9,  17.4,  11.1,  15.8,  18.7,   9.6,  13. ,
        13.3,  16.9,  20.1,  20.6,  20.9,  21. ,  19.9,  19.2,  17.6,
        17.9,  18.6,  22.4,  23.9,  23.6,  18.8,  21.2,  21.9,  23.2,
        23.4,  23.5,  22.9,  18.3,  20.3,  20.8,  17.7,  19.1,  25.6,
        25.8,  26. ,  24.3,  21.6,  26.8,  28.6,  29.5,  30.9,  31.2,
        30.8,  29.2,  26.9,  25.9,  24. ,  28. ,  28.4,  28.8,  28.9,
        28.2,  27.7,  26.5,  21.1,  24.6,  26.1,  27.1,  27.6,  28.1,
        24.4,  23.1,  27.2,  26.2,  21.3,  22.1,  22.6,  24.2,  23.7,
        25.3,  28.7,  29.4,  30.1,  29.6,  29.1,  25. ,  24.5,  25.7,
        27. ,  27.9,  26.3,  28.5,  29.7,  31.7,  32.2,  32.3,  32.4,
        30.6,  25.1,  31.8,  31.6,  32.6,  33. ,  32.5,  32.1,  31.1,
        30.3,  27.5,  29. ,  29.8,  30.7,  30.2,  29.9,  28.3,  30.5,
        30.4,  31.9,  31.4,  32.7,  32.9,  31.5,  29.3,  30. ,  32. ,
        32.8,  -9.1])

In [19]:
#Cover how many unique values are in column
data.nunique()

Date/Time           8784
Temp_C               533
Dew Point Temp_C     489
Rel Hum_%             83
Wind Speed_km/h       34
Visibility_km         24
Press_kPa            518
Weather               50
dtype: int64

In [22]:
#Counting the row
data['Temp_C'].count()

8784

In [23]:
#Counting each unique value
data['Temp_C'].value_counts()

Temp_C
 16.6    65
 1.1     58
 0.8     47
 1.5     45
 19.3    44
         ..
-20.7     1
-21.0     1
 31.8     1
 32.6     1
-21.3     1
Name: count, Length: 533, dtype: int64

In [32]:
data.head(2)

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather
0,1/1/2012 0:00,-1.8,-3.9,86,4,8.0,101.24,Fog
1,1/1/2012 1:00,-1.8,-3.7,87,4,8.0,101.24,Fog

In [31]:
#finding all the unique 'Wind Speed' values in the data
data['Wind Speed_km/h'].nunique()

34

In [30]:
#finding the number of times when the 'Weather is Exactly Clear', using value_counts()
data['Weather'].value_counts()

Weather
Mainly Clear                               2106
Mostly Cloudy                              2069
Cloudy                                     1728
Clear                                      1326
Snow                                        390
Rain                                        306
Rain Showers                                188
Fog                                         150
Rain,Fog                                    116
Drizzle,Fog                                  80
Snow Showers                                 60
Drizzle                                      41
Snow,Fog                                     37
Snow,Blowing Snow                            19
Rain,Snow                                    18
Thunderstorms,Rain Showers                   16
Haze                                         16
Drizzle,Snow,Fog                             15
Freezing Rain                                14
Freezing Drizzle,Snow                        11
Freezing Drizzle                              7
Snow,Ice Pellets                              6
Freezing Drizzle,Fog                          6
Snow,Haze                                     5
Freezing Fog                                  4
Snow Showers,Fog                              4
Moderate Snow                                 4
Rain,Snow,Ice Pellets                         4
Freezing Rain,Fog                             4
Freezing Drizzle,Haze                         3
Rain,Haze                                     3
Thunderstorms,Rain                            3
Thunderstorms,Rain Showers,Fog                3
Freezing Rain,Haze                            2
Drizzle,Snow                                  2
Rain Showers,Snow Showers                     2
Thunderstorms                                 2
Moderate Snow,Blowing Snow                    2
Rain Showers,Fog                              1
Thunderstorms,Moderate Rain Showers,Fog       1
Snow Pellets                                  1
Rain,Snow,Fog                                 1
Moderate Rain,Fog                             1
Freezing Rain,Ice Pellets,Fog                 1
Drizzle,Ice Pellets,Fog                       1
Thunderstorms,Rain,Fog                        1
Rain,Ice Pellets                              1
Rain,Snow Grains                              1
Thunderstorms,Heavy Rain Showers              1
Freezing Rain,Snow Grains                     1
Name: count, dtype: int64

In [34]:
#finding the number of times when the 'Weather is Exactly Clear', using flitring
data[data.Weather == 'Clear'].count()

Date/Time           1326
Temp_C              1326
Dew Point Temp_C    1326
Rel Hum_%           1326
Wind Speed_km/h     1326
Visibility_km       1326
Press_kPa           1326
Weather             1326
dtype: int64

In [39]:
#Filtiring Clear Weather using group by
data.groupby('Weather').get_group('Clear')

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather
67,1/3/2012 19:00,-16.9,-24.8,50,24,25.0,101.74,Clear
114,1/5/2012 18:00,-7.1,-14.4,56,11,25.0,100.71,Clear
115,1/5/2012 19:00,-9.2,-15.4,61,7,25.0,100.80,Clear
116,1/5/2012 20:00,-9.8,-15.7,62,9,25.0,100.83,Clear
117,1/5/2012 21:00,-9.0,-14.8,63,13,25.0,100.83,Clear
...,...,...,...,...,...,...,...,...
8646,12/26/2012 6:00,-13.4,-14.8,89,4,25.0,102.47,Clear
8698,12/28/2012 10:00,-6.1,-8.6,82,19,24.1,101.27,Clear
8713,12/29/2012 1:00,-11.9,-13.6,87,11,25.0,101.31,Clear
8714,12/29/2012 2:00,-11.8,-13.1,90,13,25.0,101.33,Clear
8756,12/30/2012 20:00,-13.8,-16.5,80,24,25.0,101.52,Clear

In [40]:
#fin the number of times when the 'Wind speed was exactly 4 km/h'
data['Wind Speed_km/h'].value_counts()

Wind Speed_km/h
9     830
11    791
13    735
15    719
7     677
17    666
19    616
6     609
20    496
4     474
22    439
24    374
0     309
26    242
28    205
30    161
32    139
33     85
35     53
37     45
39     24
41     22
44     14
43     13
48     13
46     11
52      7
57      5
50      4
2       2
83      1
70      1
63      1
54      1
Name: count, dtype: int64

In [41]:
#finding how many null values in the data
data.isnull().sum()

Date/Time           0
Temp_C              0
Dew Point Temp_C    0
Rel Hum_%           0
Wind Speed_km/h     0
Visibility_km       0
Press_kPa           0
Weather             0
dtype: int64

In [45]:
#Renamin the column 'Weather' to 'Weather Condition'
data.rename(columns = {'Weather' : 'Weather Condition'})

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather Condition
0,1/1/2012 0:00,-1.8,-3.9,86,4,8.0,101.24,Fog
1,1/1/2012 1:00,-1.8,-3.7,87,4,8.0,101.24,Fog
2,1/1/2012 2:00,-1.8,-3.4,89,7,4.0,101.26,"Freezing Drizzle,Fog"
3,1/1/2012 3:00,-1.5,-3.2,88,6,4.0,101.27,"Freezing Drizzle,Fog"
4,1/1/2012 4:00,-1.5,-3.3,88,7,4.8,101.23,Fog
...,...,...,...,...,...,...,...,...
8779,12/31/2012 19:00,0.1,-2.7,81,30,9.7,100.13,Snow
8780,12/31/2012 20:00,0.2,-2.4,83,24,9.7,100.03,Snow
8781,12/31/2012 21:00,-0.5,-1.5,93,28,4.8,99.95,Snow
8782,12/31/2012 22:00,-0.2,-1.8,89,28,9.7,99.91,Snow
8783,12/31/2012 23:00,0.0,-2.1,86,30,11.3,99.89,Snow

In [46]:
#Calculating the Mean of Visibility_km column
data['Visibility_km'].mean()

27.664446721311478

In [49]:
#Calculating the Standard Deviation of 'pressure'
data['Press_kPa'].std()

0.8440047459486483

In [50]:
#What is the Variance of 'Relative Humidity'
data['Rel Hum_%'].var()

286.24855019850196

In [55]:
#Finding all the instances when 'Snow' Was recoreded
data['Weather'].value_counts()

Weather
Mainly Clear                               2106
Mostly Cloudy                              2069
Cloudy                                     1728
Clear                                      1326
Snow                                        390
Rain                                        306
Rain Showers                                188
Fog                                         150
Rain,Fog                                    116
Drizzle,Fog                                  80
Snow Showers                                 60
Drizzle                                      41
Snow,Fog                                     37
Snow,Blowing Snow                            19
Rain,Snow                                    18
Thunderstorms,Rain Showers                   16
Haze                                         16
Drizzle,Snow,Fog                             15
Freezing Rain                                14
Freezing Drizzle,Snow                        11
Freezing Drizzle                              7
Snow,Ice Pellets                              6
Freezing Drizzle,Fog                          6
Snow,Haze                                     5
Freezing Fog                                  4
Snow Showers,Fog                              4
Moderate Snow                                 4
Rain,Snow,Ice Pellets                         4
Freezing Rain,Fog                             4
Freezing Drizzle,Haze                         3
Rain,Haze                                     3
Thunderstorms,Rain                            3
Thunderstorms,Rain Showers,Fog                3
Freezing Rain,Haze                            2
Drizzle,Snow                                  2
Rain Showers,Snow Showers                     2
Thunderstorms                                 2
Moderate Snow,Blowing Snow                    2
Rain Showers,Fog                              1
Thunderstorms,Moderate Rain Showers,Fog       1
Snow Pellets                                  1
Rain,Snow,Fog                                 1
Moderate Rain,Fog                             1
Freezing Rain,Ice Pellets,Fog                 1
Drizzle,Ice Pellets,Fog                       1
Thunderstorms,Rain,Fog                        1
Rain,Ice Pellets                              1
Rain,Snow Grains                              1
Thunderstorms,Heavy Rain Showers              1
Freezing Rain,Snow Grains                     1
Name: count, dtype: int64

In [61]:
data[data['Weather'] == 'Snow']

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather
55,1/3/2012 7:00,-14.0,-19.5,63,19,25.0,100.95,Snow
84,1/4/2012 12:00,-13.7,-21.7,51,11,24.1,101.25,Snow
86,1/4/2012 14:00,-11.3,-19.0,53,7,19.3,100.97,Snow
87,1/4/2012 15:00,-10.2,-16.3,61,11,9.7,100.89,Snow
88,1/4/2012 16:00,-9.4,-15.5,61,13,19.3,100.79,Snow
...,...,...,...,...,...,...,...,...
8779,12/31/2012 19:00,0.1,-2.7,81,30,9.7,100.13,Snow
8780,12/31/2012 20:00,0.2,-2.4,83,24,9.7,100.03,Snow
8781,12/31/2012 21:00,-0.5,-1.5,93,28,4.8,99.95,Snow
8782,12/31/2012 22:00,-0.2,-1.8,89,28,9.7,99.91,Snow
8783,12/31/2012 23:00,0.0,-2.1,86,30,11.3,99.89,Snow

In [66]:
#Using str.contains
data[data['Weather'].str.contains('Snow')]

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather
41,1/2/2012 17:00,-2.1,-9.5,57,22,25.0,99.66,Snow Showers
44,1/2/2012 20:00,-5.6,-13.4,54,24,25.0,100.07,Snow Showers
45,1/2/2012 21:00,-5.8,-12.8,58,26,25.0,100.15,Snow Showers
47,1/2/2012 23:00,-7.4,-14.1,59,17,19.3,100.27,Snow Showers
48,1/3/2012 0:00,-9.0,-16.0,57,28,25.0,100.35,Snow Showers
...,...,...,...,...,...,...,...,...
8779,12/31/2012 19:00,0.1,-2.7,81,30,9.7,100.13,Snow
8780,12/31/2012 20:00,0.2,-2.4,83,24,9.7,100.03,Snow
8781,12/31/2012 21:00,-0.5,-1.5,93,28,4.8,99.95,Snow
8782,12/31/2012 22:00,-0.2,-1.8,89,28,9.7,99.91,Snow
8783,12/31/2012 23:00,0.0,-2.1,86,30,11.3,99.89,Snow

In [70]:
#Finding all the instances when 'Wind Speed is above 24' and 'Visibility is 25'
data[(data['Wind Speed_km/h'] >= 24) & (data['Visibility_km'] == 25)]

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather
23,1/1/2012 23:00,5.3,2.0,79,30,25.0,99.31,Cloudy
24,1/2/2012 0:00,5.2,1.5,77,35,25.0,99.26,Rain Showers
25,1/2/2012 1:00,4.6,0.0,72,39,25.0,99.26,Cloudy
26,1/2/2012 2:00,3.9,-0.9,71,32,25.0,99.26,Mostly Cloudy
27,1/2/2012 3:00,3.7,-1.5,69,33,25.0,99.30,Mostly Cloudy
...,...,...,...,...,...,...,...,...
8754,12/30/2012 18:00,-12.6,-16.0,76,24,25.0,101.36,Mainly Clear
8755,12/30/2012 19:00,-13.4,-16.5,77,26,25.0,101.47,Mainly Clear
8756,12/30/2012 20:00,-13.8,-16.5,80,24,25.0,101.52,Clear
8759,12/30/2012 23:00,-12.1,-15.1,78,28,25.0,101.52,Mostly Cloudy
8760,12/31/2012 0:00,-11.1,-14.4,77,26,25.0,101.51,Cloudy

In [83]:
#What is the Minimum % Maximum value of each column against each 'Weather'
data.groupby('Visibility_km').min()

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Press_kPa,Weather
Visibility_km,,,,,,,
0.2,3/17/2012 10:00,-0.1,-0.4,98,0,102.09,Fog
0.4,10/20/2012 6:00,8.8,7.7,93,4,99.87,Fog
0.6,1/12/2012 16:00,-5.5,-7.3,83,4,99.88,Fog
0.8,1/12/2012 15:00,-19.0,-22.9,71,0,99.90,Fog
1.0,1/12/2012 17:00,-8.2,-12.0,74,4,99.07,"Drizzle,Fog"
1.2,1/1/2012 10:00,-8.8,-12.1,75,9,97.99,Fog
1.6,1/13/2012 17:00,-8.3,-12.3,72,4,98.23,"Drizzle,Fog"
2.0,1/12/2012 11:00,-7.9,-9.6,76,0,98.07,"Drizzle,Fog"
2.4,1/13/2012 0:00,-14.4,-16.3,59,4,98.65,"Drizzle,Fog"
2.8,1/17/2012 12:00,-11.8,-16.0,71,6,98.03,"Drizzle,Fog"
3.2,1/12/2012 23:00,-11.3,-16.1,68,0,97.97,"Drizzle,Fog"
3.6,1/17/2012 5:00,-9.1,-10.4,85,6,97.75,"Drizzle,Fog"
4.0,1/1/2012 11:00,-11.3,-13.3,69,0,98.00,"Drizzle,Fog"
4.8,1/1/2012 12:00,-13.4,-16.2,71,0,98.07,"Drizzle,Fog"
6.4,1/1/2012 15:00,-14.8,-15.9,69,0,98.06,Drizzle
8.0,1/1/2012 0:00,-14.8,-17.2,62,0,97.89,Drizzle
9.7,1/10/2012 5:00,-16.0,-17.2,61,0,97.58,Drizzle
11.3,1/13/2012 4:00,-12.3,-16.2,63,2,97.52,Clear
12.9,1/1/2012 16:00,-18.6,-22.8,59,0,97.76,Clear
16.1,1/1/2012 17:00,-19.5,-23.4,40,0,98.32,Clear
19.3,1/1/2012 22:00,-14.7,-20.9,40,0,98.16,Clear
24.1,1/10/2012 10:00,-23.3,-28.5,30,0,98.47,Clear
25.0,1/1/2012 20:00,-23.2,-28.5,21,0,97.56,Clear
48.3,1/14/2012 12:00,-22.2,-27.8,18,0,98.64,Clear

In [84]:
#Maximum
data.groupby('Visibility_km').max()

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Press_kPa,Weather
Visibility_km,,,,,,,
0.2,3/17/2012 9:00,2.7,2.6,100,4,102.39,Freezing Fog
0.4,5/2/2012 3:00,10.6,10.6,100,4,101.49,Fog
0.6,5/2/2012 1:00,11.7,11.7,100,48,102.34,"Snow,Blowing Snow"
0.8,3/17/2012 5:00,0.6,-0.3,99,39,102.85,Moderate Snow
1.0,5/2/2012 7:00,12.7,12.5,99,33,101.70,Snow
1.2,5/2/2012 4:00,8.6,7.5,96,44,101.52,"Snow,Fog"
1.6,5/2/2012 6:00,11.4,11.4,100,41,102.05,"Snow,Fog"
2.0,5/22/2012 6:00,18.2,16.1,99,37,102.02,"Snow,Fog"
2.4,5/9/2012 6:00,13.7,12.2,99,37,101.71,"Thunderstorms,Heavy Rain Showers"
2.8,3/9/2012 0:00,12.4,12.0,99,33,101.54,"Snow,Ice Pellets"
3.2,7/17/2012 6:00,19.6,18.5,100,35,102.07,"Thunderstorms,Moderate Rain Showers,Fog"
3.6,5/4/2012 8:00,13.7,12.1,100,28,100.83,"Snow,Fog"
4.0,5/9/2012 9:00,15.1,13.8,99,41,102.52,"Snow,Haze"
4.8,8/10/2012 19:00,20.6,18.6,99,37,102.02,"Thunderstorms,Rain,Fog"
6.4,9/30/2012 2:00,25.5,23.1,99,46,102.64,"Thunderstorms,Rain Showers"
8.0,9/30/2012 20:00,21.7,19.3,100,46,103.04,"Snow,Ice Pellets"
9.7,9/30/2012 21:00,22.9,21.3,100,46,102.69,"Thunderstorms,Rain Showers,Fog"
11.3,9/22/2012 1:00,20.2,18.6,97,44,102.61,"Snow,Ice Pellets"
12.9,9/4/2012 20:00,25.2,23.0,98,46,102.91,"Thunderstorms,Rain Showers"
16.1,9/8/2012 15:00,28.3,22.9,99,52,102.99,"Thunderstorms,Rain Showers"
19.3,9/8/2012 9:00,29.4,22.6,99,48,102.90,"Thunderstorms,Rain Showers"
24.1,9/9/2012 8:00,33.0,24.4,99,57,103.65,"Thunderstorms,Rain Showers"
25.0,9/9/2012 5:00,30.1,21.9,99,83,103.63,"Thunderstorms,Rain Showers"
48.3,9/9/2012 9:00,33.0,20.9,100,63,103.59,Snow Showers

In [85]:
#All the Records where wheather condition is Fog
data.groupby('Weather').get_group('Fog')

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather
0,1/1/2012 0:00,-1.8,-3.9,86,4,8.0,101.24,Fog
1,1/1/2012 1:00,-1.8,-3.7,87,4,8.0,101.24,Fog
4,1/1/2012 4:00,-1.5,-3.3,88,7,4.8,101.23,Fog
5,1/1/2012 5:00,-1.4,-3.3,87,9,6.4,101.27,Fog
6,1/1/2012 6:00,-1.5,-3.1,89,7,6.4,101.29,Fog
...,...,...,...,...,...,...,...,...
8716,12/29/2012 4:00,-16.0,-17.2,90,6,9.7,101.25,Fog
8717,12/29/2012 5:00,-14.8,-15.9,91,4,6.4,101.25,Fog
8718,12/29/2012 6:00,-13.8,-15.3,88,4,9.7,101.25,Fog
8719,12/29/2012 7:00,-14.8,-16.4,88,7,8.0,101.22,Fog
8722,12/29/2012 10:00,-12.0,-13.3,90,7,6.4,101.15,Fog

In [86]:
#Find all the instances when 'Weather is Clear' or 'Visibility is above 40'
data[(data['Weather'] == 'Clear') & (data['Visibility_km'] > 40)]

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather
351,1/15/2012 15:00,-15.4,-22.8,53,24,48.3,102.71,Clear
352,1/15/2012 16:00,-15.1,-22.8,52,24,48.3,102.79,Clear
425,1/18/2012 17:00,-11.3,-18.8,54,26,48.3,101.54,Clear
440,1/19/2012 8:00,-13.7,-18.4,68,19,48.3,101.84,Clear
441,1/19/2012 9:00,-12.7,-17.2,69,17,48.3,101.73,Clear
...,...,...,...,...,...,...,...,...
8384,12/15/2012 8:00,-10.7,-15.6,67,13,48.3,102.69,Clear
8385,12/15/2012 9:00,-10.4,-15.9,64,19,48.3,102.74,Clear
8389,12/15/2012 13:00,-8.4,-14.7,60,19,48.3,102.64,Clear
8631,12/25/2012 15:00,-7.1,-13.7,59,17,48.3,101.98,Clear
8632,12/25/2012 16:00,-7.5,-13.9,60,11,48.3,102.03,Clear

In [88]:
#Finding the instances when 'Weather is Clear' and 'Relative Humidity is greater then 50' or 'Visibility is above 40'
data[(data['Weather'] == 'Clear') & (data['Rel Hum_%'] > 50) | (data['Visibility_km'] > 40)]

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather
106,1/5/2012 10:00,-6.0,-10.0,73,17,48.3,100.45,Mainly Clear
107,1/5/2012 11:00,-5.6,-10.2,70,22,48.3,100.41,Mainly Clear
108,1/5/2012 12:00,-4.7,-9.6,69,20,48.3,100.38,Mainly Clear
109,1/5/2012 13:00,-4.4,-9.7,66,26,48.3,100.40,Mainly Clear
110,1/5/2012 14:00,-5.1,-10.7,65,22,48.3,100.46,Mainly Clear
...,...,...,...,...,...,...,...,...
8749,12/30/2012 13:00,-12.4,-16.2,73,37,48.3,100.92,Mostly Cloudy
8750,12/30/2012 14:00,-11.8,-16.1,70,37,48.3,100.96,Mainly Clear
8751,12/30/2012 15:00,-11.3,-15.6,70,32,48.3,101.05,Mainly Clear
8752,12/30/2012 16:00,-11.4,-15.5,72,26,48.3,101.15,Mainly Clear
8756,12/30/2012 20:00,-13.8,-16.5,80,24,25.0,101.52,Clear